using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OracleClient;
using System.Web.UI.WebControls;
using Telerik.Web;
using Telerik.Web.UI;

public partial class DefaultCS : System.Web.UI.Page
{

    protected void Page_Load(object sender, EventArgs e)
    {
        if (!IsPostBack)
        {
            string source = WebTools.GetExpr("SOURCE", "IPMS_SYS_EXPORT", "EXPT_ID=" + Request.QueryString["ReportID"]);

            string ReportName = WebTools.GetExpr("EXPT_TITLE", "IPMS_SYS_EXPORT", "EXPT_ID=" + Request.QueryString["ReportID"]);
            string CLIENT_NAME = WebTools.GetExpr("REMARKS", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());
            string JOB_CODE = WebTools.GetExpr("JOB_CODE", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());
            string JOB_NAME = WebTools.GetExpr("JOB_NAME", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());
            string APP_LOGO1 = WebTools.GetExpr("APP_LOGO1", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());
            string APP_LOGO2 = WebTools.GetExpr("APP_LOGO2", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());
            string APP_LOGO3 = WebTools.GetExpr("APP_LOGO3", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());
            string PROJ_DESC = WebTools.GetExpr("PROJ_DESC", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());
            string JV_OF = WebTools.GetExpr("JV_OF", "PROJECT_INFORMATION", "PROJECT_ID=" + Session["PROJECT_ID"].ToString());

            Master.HeadingMessage = ReportName + " Report";

            string headerMiddleCell = "<h3>" + CLIENT_NAME + "</h3>" + "<h2>" + ReportName + "</h2>";
            string headerLeftCell = "<img src=\"~\\Images\\Company_Logo\\ADNOC.png\" style=\"width:64px; height: 64px;\" />";
            string headerRightCell = "<img src=\"~\\Images\\Company_Logo\\CPECC_LOGO.png\" style=\"width:64px; height: 64px;\" />";
            string footerMiddleCell = "Page Num. : <?page-number?>";
            string footerRightCell = "<b> Date : " + DateTime.Now.ToString("dddd, dd MMMM yyyy h:mm tt" + "</b>");


            RadGrid1.ExportSettings.Pdf.BorderType = GridPdfSettings.GridPdfBorderType.AllBorders;
            RadGrid1.ExportSettings.Pdf.PageHeader.MiddleCell.Text = headerMiddleCell;
            RadGrid1.ExportSettings.Pdf.PageHeader.MiddleCell.TextAlign = GridPdfPageHeaderFooterCell.CellTextAlign.Center;
            RadGrid1.ExportSettings.Pdf.PageHeader.LeftCell.Text = headerLeftCell;
            RadGrid1.ExportSettings.Pdf.PageHeader.LeftCell.TextAlign = GridPdfPageHeaderFooterCell.CellTextAlign.Center;
            RadGrid1.ExportSettings.Pdf.PageHeader.RightCell.Text = headerRightCell;
            RadGrid1.ExportSettings.Pdf.PageHeader.RightCell.TextAlign = GridPdfPageHeaderFooterCell.CellTextAlign.Center;
            RadGrid1.ExportSettings.Pdf.PageFooter.MiddleCell.Text = footerMiddleCell;
            RadGrid1.ExportSettings.Pdf.PageFooter.MiddleCell.TextAlign = GridPdfPageHeaderFooterCell.CellTextAlign.Center;
            RadGrid1.ExportSettings.Pdf.PageFooter.RightCell.Text = footerRightCell;
            RadGrid1.ExportSettings.Pdf.PageFooter.RightCell.TextAlign = GridPdfPageHeaderFooterCell.CellTextAlign.Center;

            DataTable dt = new DataTable();
            String ConnString = ConfigurationManager.ConnectionStrings["ipmsConnectionString"].ConnectionString;
            OracleConnection con = new OracleConnection(ConnString);
            OracleCommand cmd = new OracleCommand("SELECT * FROM " + source + " where 1=2", con);
            cmd.CommandType = CommandType.Text;
           OracleDataAdapter da = new OracleDataAdapter(cmd);

            System.Data.DataTable result = new System.Data.DataTable();
            da.Fill(result);

            List<string> columns = new List<string>();
            foreach (DataColumn item in result.Columns)
            {

                ddlSelectColumn.Items.Add(item.ColumnName);

            }
            RadGrid1.ExportSettings.FileName = ReportName;
        }
        
    }
    protected void RadGrid1_ItemCreated(object sender, GridItemEventArgs e)
    {
        if (e.Item is GridHeaderItem && RadGrid1.IsExporting)
        {
            GridHeaderItem item = e.Item as GridHeaderItem;
            foreach (GridColumn col in RadGrid1.MasterTableView.AutoGeneratedColumns)
            {
                if (col.HeaderStyle.Width.Type == UnitType.Percentage)
                {
                    double size = RadGrid1.Width.Value;
                    Unit unit = new Unit(size * col.HeaderStyle.Width.Value / 100, RadGrid1.Width.Type);
                    col.HeaderStyle.Width = unit;
                }
            }

        }
        if (RadGrid1.IsExporting)
        {
          FormatGridItem(e.Item);
        }

    }

    protected void FormatGridItem(GridItem item)
    {
        item.Style["color"] = "#000000";

        if (item is GridDataItem)
        {
            item.Style["vertical-align"] = "middle";
            item.Style["text-align"] = "left";

        }

        switch (item.ItemType)
        {
            //case GridItemType.Item: item.Style["background-color"] = "#888888"; break;
            //case GridItemType.AlternatingItem: item.Style["background-color"] = "#DDDDDD"; break;
            case GridItemType.Header: item.Style["background-color"] = "#BBBBBB"; break;
            //case GridItemType.CommandItem: item.Style["background-color"] = "#000000"; break;

        }

        //foreach (GridColumn col in RadGrid1.MasterTableView.AutoGeneratedColumns)
        //{
        //    col.HeaderText = col.UniqueName.ToString().Replace('_', ' ');

        //}

        //if (item is GridCommandItem)
        //{
        //    item.PrepareItemStyle();
        //}
    }

    protected void RadGrid1_NeedDataSource(object sender, GridNeedDataSourceEventArgs e)
    {
        RadGrid1.DataSource = GetDataSource();
    }
    protected void RadGrid1_PreRender(object sender, EventArgs e)
    {
        

        if (RadGrid1.IsExporting)
        {
            foreach (GridCommandItem item in RadGrid1.MasterTableView.GetItems(GridItemType.CommandItem))
            {
                item.Visible = false;
            }

        }
       
    }
    protected DataTable GetDataSource()
    {
        string source = WebTools.GetExpr("SOURCE", "IPMS_SYS_EXPORT", "EXPT_ID=" + Request.QueryString["ReportID"]);
        
        DataTable dt = new DataTable();
        String ConnString = ConfigurationManager.ConnectionStrings["ipmsConnectionString"].ConnectionString;
        OracleConnection con = new OracleConnection(ConnString);
        var collection = ddlSelectColumn.CheckedItems;
        if (collection.Count > 0)
        {
            string q = "";
            foreach (var item in collection)
            {
                q += item.Text + ",";
            }
            q = q.Substring(0, q.Length - 1);
           
            string query = "SELECT " + q + " FROM " + source;
            OracleCommand cmd = new OracleCommand(query, con);
            cmd.CommandType = CommandType.Text;
            OracleDataAdapter da = new OracleDataAdapter(cmd);
            da.Fill(dt);
            
            
        }

        else
        {
            OracleCommand cmd = new OracleCommand("SELECT * from " + source, con);
            cmd.CommandType = CommandType.Text;
            OracleDataAdapter da = new OracleDataAdapter(cmd);
            da.Fill(dt);
        }


        return dt;
    }


    protected void ddlSelectColumn_SelectedIndexChanged(object sender, RadComboBoxSelectedIndexChangedEventArgs e)
    {
        //try
        //{

            RadGrid1.DataSource = GetDataSource();
            RadGrid1.Rebind();
       // }
        //catch (Exception ex)
        //{
        //    Master.ShowError("Please Select Filter & Sorting columns");
        //}
    }

 protected void RadGrid1_ColumnCreated(object sender, GridColumnCreatedEventArgs e)
    {
        if (e.Column.UniqueName.Contains("PROJ"))
        {
            e.Column.Visible = false;
        }
        if (e.Column is GridDateTimeColumn)
        {
            (e.Column as GridDateTimeColumn).DataFormatString = "{0:dd-MMM-yyyy}";
        }
    }
    protected void ddlReportSelect_SelectedIndexChanged(object sender, RadComboBoxSelectedIndexChangedEventArgs e)
    {
        string report_id = ddlReportSelect.SelectedValue.ToString();
        if (report_id != "")
        {

            Response.Redirect("~/Home/FilterRdlc.aspx?ReportID=" + ddlReportSelect.SelectedValue.ToString());
        }
        else
        {
            Master.ShowWarn("Select Report");
        }
    }

}

